name: moons-metrology
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scipy
  - jupyterlab
  - ipykernel
  - scikit-learn
  - pip
  - pip:
    - python-dotenv
    - mkdocs
    - pillow
    - scikit-spatial
    - -e .